"""Tessendorf FFT ocean ("Simulating Ocean Water", doc/coursenotes2004.pdf).

The height field is a sum of sinusoids whose amplitudes come from the Phillips
spectrum and whose phases evolve with the deep-water dispersion relation
w(k) = sqrt(g*|k|). Evaluating that sum is an inverse 2D FFT each frame -- the
single hot loop, and the thing we accelerate on the GPU.

All array maths goes through `backend.xp`, so an instance built with the numpy
backend and one built with the cupy backend run identical code on CPU vs GPU.
The random spectrum seed is generated on the CPU and uploaded, so both backends
produce a bit-for-bit matching surface (handy for verifying correctness).
"""

from __future__ import annotations

import numpy as np

from config import OceanParams
from src.backend import Backend


class Ocean:
    def __init__(self, backend: Backend, params: OceanParams, seed: int = 1234):
        self.backend = backend
        self.xp = backend.xp
        self.params = params.copy()
        self.seed = seed
        # Real-space fields produced by step(); populated each frame. Declared
        # here so the object's full shape is visible and pack_*() never hits a
        # missing attribute before the first step.
        self.height = self.dx = self.dz = self.sx = self.sz = None
        self._build()

    # ------------------------------------------------------------------ setup
    def _build(self) -> None:
        """Precompute everything that doesn't depend on time: the wavenumber
        grid, the dispersion relation, and the initial spectrum h0(k)."""
        xp = self.xp
        p = self.params
        N, L = p.N, p.L

        # Angular wavenumbers along each axis: k = 2*pi * (n / L), n in [-N/2,N/2)
        n = np.fft.fftfreq(N, d=L / N) * (2.0 * np.pi)
        kx, kz = np.meshgrid(n, n, indexing="ij")
        kmag = np.sqrt(kx * kx + kz * kz)
        kmag_safe = np.where(kmag == 0.0, 1.0, kmag)

        # Phillips spectrum (host-side, float64 for accuracy, with a fixed seed
        # so CPU and GPU surfaces match exactly).
        phillips = self._phillips(kx, kz, kmag, kmag_safe)
        rng = np.random.default_rng(self.seed)
        gr = rng.standard_normal((N, N))
        gi = rng.standard_normal((N, N))
        h0 = (gr + 1j * gi) * np.sqrt(phillips / 2.0)

        # conj(h0(-k)): mirror the indices (n -> -n) and conjugate.
        h0_mk = np.conj(self._mirror(h0))

        # Dispersion relation w(k) = sqrt(g |k|).
        w = np.sqrt(p.gravity * kmag)

        # Upload constant fields to the active backend as the right dtypes.
        c64, f32 = xp.complex64, xp.float32
        self._h0 = xp.asarray(h0, dtype=c64)
        self._h0_mk = xp.asarray(h0_mk, dtype=c64)
        self._w = xp.asarray(w, dtype=f32)
        self._kx = xp.asarray(kx, dtype=f32)
        self._kz = xp.asarray(kz, dtype=f32)
        self._kmag_safe = xp.asarray(kmag_safe, dtype=f32)
        # Reusable host buffers for the two GL textures uploaded each frame:
        #   displacement = (height, Dx, Dz, 0)
        #   slope        = (dH/dx, dH/dz, 0, 0)  -> seamless per-fragment normals
        self._packed = np.empty((N, N, 4), dtype=np.float32)
        self._packed_n = np.zeros((N, N, 4), dtype=np.float32)

    def _phillips(self, kx, kz, kmag, kmag_safe) -> np.ndarray:
        p = self.params
        # Largest wave generated by wind of speed V: L_w = V^2 / g.
        Lw = p.wind_speed * p.wind_speed / p.gravity
        ang = np.radians(p.wind_dir_deg)
        wx, wz = np.cos(ang), np.sin(ang)

        k_hat_x = kx / kmag_safe
        k_hat_z = kz / kmag_safe
        k_dot_w = k_hat_x * wx + k_hat_z * wz  # cos(angle to wind)

        k2 = kmag_safe * kmag_safe
        k4 = k2 * k2
        ph = (
            p.amplitude
            * np.exp(-1.0 / (k2 * Lw * Lw))
            / k4
            * (k_dot_w * k_dot_w)              # directional weighting
        )
        # Suppress waves far smaller than `small_wave` (anti-aliasing).
        ph *= np.exp(-k2 * p.small_wave * p.small_wave)
        # Drop waves travelling against the wind and the k=0 singularity.
        ph = np.where(k_dot_w < 0.0, ph * 0.07, ph)
        ph[kmag == 0.0] = 0.0
        return ph

    @staticmethod
    def _mirror(a: np.ndarray) -> np.ndarray:
        """a[(-i)%N, (-j)%N] -- the value at the mirrored wavevector -k."""
        return np.roll(np.roll(a[::-1, ::-1], 1, axis=0), 1, axis=1)

    # ------------------------------------------------------------- simulation
    def step(self, t: float) -> None:
        """Advance the spectrum to time t (already time-scaled by the caller)
        and inverse-FFT to real-space fields.

        Produces:
          self.height  (N,N) float32 vertical displacement
          self.dx,self.dz  (N,N) float32 horizontal (choppy) displacement
        All live on the active backend (GPU arrays under cupy)."""
        xp = self.xp
        wt = self._w * t
        c = xp.cos(wt)
        s = xp.sin(wt)
        # h(k,t) = h0 e^{i w t} + conj(h0(-k)) e^{-i w t}
        hk = self._h0 * (c + 1j * s) + self._h0_mk * (c - 1j * s)

        # Vertical height = inverse FFT of the spectrum.
        self.height = xp.real(xp.fft.ifft2(hk)).astype(xp.float32)

        # Horizontal displacement (choppiness): D = IFFT(-i * k/|k| * h)
        lam = self.params.choppiness
        disp_x = xp.fft.ifft2(-1j * self._kx / self._kmag_safe * hk)
        disp_z = xp.fft.ifft2(-1j * self._kz / self._kmag_safe * hk)
        self.dx = (lam * xp.real(disp_x)).astype(xp.float32)
        self.dz = (lam * xp.real(disp_z)).astype(xp.float32)

        # Surface slopes: gradient of height = IFFT(i * k * h). Used for exact,
        # periodic per-fragment normals (no finite-difference seams).
        self.sx = xp.real(xp.fft.ifft2(1j * self._kx * hk)).astype(xp.float32)
        self.sz = xp.real(xp.fft.ifft2(1j * self._kz * hk)).astype(xp.float32)

    def pack_texture(self) -> np.ndarray:
        """Return a contiguous host (N,N,4) float32 array packing
        (height, Dx, Dz, foam) for upload to the GL displacement texture.
        The device->host copy here is the GPU readback cost."""
        b = self.backend
        h = b.to_cpu(self.height)
        dx = b.to_cpu(self.dx)
        dz = b.to_cpu(self.dz)
        self._packed[..., 0] = h
        self._packed[..., 1] = dx
        self._packed[..., 2] = dz
        self._packed[..., 3] = 0.0
        return self._packed

    def pack_normal(self) -> np.ndarray:
        """Return a contiguous host (N,N,4) float32 array packing the surface
        slopes (dH/dx, dH/dz) for the shading normal."""
        b = self.backend
        self._packed_n[..., 0] = b.to_cpu(self.sx)
        self._packed_n[..., 1] = b.to_cpu(self.sz)
        return self._packed_n

    # ------------------------------------------------------------- live edits
    def update_params(self, params: OceanParams) -> None:
        """Apply new parameters. Resolution / patch changes rebuild the
        spectrum; cheap tweaks (choppiness, time_scale) are applied in-place."""
        old = self.params
        needs_rebuild = (
            params.N != old.N
            or params.L != old.L
            or params.wind_speed != old.wind_speed
            or params.wind_dir_deg != old.wind_dir_deg
            or params.amplitude != old.amplitude
            or params.small_wave != old.small_wave
        )
        self.params = params.copy()
        if needs_rebuild:
            self._build()
